### ISSUE TITLE
Feed per category

### ISSUE THREAD

**Issue by Fryboyter** [bolt/bolt-extension-rssfeed#22]
Hello,

i am running a site with wordpress. Some of the articles under a certain category are published on an other side (osbn.de (not mine)). This sides fetches the articles with an rss feed which contains just the articles under this certain category (http://www.example.com/category/categoryname/feed for instance).

Because am not very happy with Wordpress i want to switch to Bolt CMS. Do you see a chance that this extension will support feeds per category in the near future? Unfortunately i am not a programmer and therefore i am not able to alter this extension by myself or create a new one and i am not very comfortable with the workaround i posted under https://discuss.bolt.cm/d/652-feed-per-category.

Thank you very much in advance for your answer.
Jens

**Comment by jdhartwell** [comment]
Did you come to a solid solution for this 'feeds per category'?
