### ISSUE TITLE
Variable "canonical" does not exist in "rss.twig" at line 5.

### ISSUE THREAD

**Issue by pentatonicfunk** [bolt/bolt-extension-rssfeed#23]
Twig_Error_Runtime in Template.php line 487:
Variable "canonical" does not exist in "rss.twig" at line 5.

**Comment by bobdenotter** [comment]
Needs more info.. Version of the extension? Version of Bolt? How? When?
Where?

**Comment by pentatonicfunk** [comment]
Extension Version 4.0
Bolt Version : 3.2.14
How, when, where : open <yoursite>/rss/feed.xml

**Comment by bobdenotter** [comment]
Thanks, I can reproduce. 👍 

PR in #24.
