### ISSUE TITLE
Markdown support / doc suggestion

### ISSUE THREAD

**Issue by doenietzomoeilijk** [bolt/bolt-extension-rssfeed#9]
Before I start turning in silly PRs, I'd like to discuss this with you first:
- I kinda stumbled upon being able to override the default template, by having a file in my theme folder. The default config tells me that overriding templates should live in the 'assets' directory, but never mentions anything about themes. This could be me being new to Bolt in general, but the docs might benefit from giving slightly more info on overriding the template. I'm more than willing to write some words, would that be welcome?
- My posts have a markdown field for the body, and I'd like the content to be rendered in the feed. I'm sure there's more than one way to set this up, but if I want to keep using rssSafe I'd have to change that. I tried grabbing `$record->getDecodedValue($field)` rather than `$record->values[$field]`, but that only works when I echo it, running it through Maid gives me back an empty result. Any idea why that is? Or should I just drop the rssSafe (I'm the sole author and I somewhat trust myself...)?

**Comment by GawainLynch** [comment]
#### Template overrides

Yeah, by all means update the docs. Most of these just assume a basic knowledge of Twig… but Twig docs are +/- in some ways.

Basically if you set up something like 
```
pages:
    enabled: true
    feed_template: rss.twig
```

What Twig will do is first look in the Bolt defined paths for `rss.twig`, then in the root of the active theme, then in the extension's `assets/` folder

You can even add relative paths, like `foo/bar/rss.twig`, e.g. I usually set up something like
```
pages:
    enabled: true
    feed_template: extensions/rss/rss.twig
```
…and in my theme directory create `extensions/rss/` and add the Twig file there

**Comment by GawainLynch** [comment]
#### Markdown

Just create a separate Twig template for that ContentType and use the Twig `|markdown` filter that comes with Bolt, e.g.:
```twig
{{ record.foobar|markdown }} 
```

**Comment by doenietzomoeilijk** [comment]
re template overrides: that's actually better than I hoped for - I was wondering whether there would be a generic way of overriding plugin templates, guess that's a yes. :) Maybe the wording in the config could be slightly altered, but this is more of a Bolt thing, then, worth mentioning somewhere in the template section. That's where I expected it most.

re Markdown: yeah, that's what I did. I figured I didn't *really* need the HTML scrubbing. Just in case I ever *do* feel the need, what would be the best way to go about combining the two? Would it make sense to have the plugin auto-parse any markdown fields in the record, or make that a switchable behaviour?

**Comment by GawainLynch** [comment]
> but this is more of a Bolt thing, then, worth mentioning somewhere in the template section. That's where I expected it most.

It's a Twig thing very specifically. We don't try to cover off too much documentation of upstream libraries, generally speaking, as… resources :grin: 

> Would it make sense to have the plugin auto-parse any markdown fields in the record, or make that a switchable behaviour?

No, that belongs in a custom template. Markdown is loved by many, but not fabulous on performance. so impacting every single call for every single user doesn't make sense.

**Comment by doenietzomoeilijk** [comment]
> It's a Twig thing very specifically. We don't try to cover off too much documentation of upstream libraries, generally speaking, as… resources :grin:

OK, that makes sense then. Just something you'd have to know.

> No, that belongs in a custom template. Markdown is loved by many, but not fabulous on performance. so impacting every single call for every single user doesn't make sense.

Fair enough. Maybe worth mentioning in a readme somewhere, then?

**Comment by bobdenotter** [comment]
Bit of a late reply, but the extension supports markdown now.
